# Generated by Django 3.2.5 on 2023-06-20 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_id', models.AutoField(primary_key=True, serialize=False)),
                ('claim_type', models.CharField(max_length=100)),
                ('claim_description', models.CharField(max_length=1000)),
                ('claim_status', models.CharField(default='En proceso', max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.order')),
            ],
        ),
    ]
