# Generated by Django 3.2.5 on 2023-06-20 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_claim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claim_description',
            new_name='Descripcion_de_reclamo',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='claim_type',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='order',
            new_name='Orden',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='claim_status',
        ),
        migrations.AddField(
            model_name='claim',
            name='Correo',
            field=models.EmailField(default='su_correo@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='Fecha',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='Tipo_de_reclamo',
            field=models.CharField(default='Reclamo', max_length=100),
        ),
    ]
