# Generated by Django 3.2.5 on 2023-06-20 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20230619_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('client_lastname', models.CharField(max_length=100)),
                ('client_address', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=100)),
                ('client_email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.client')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.order')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.invoice'),
        ),
    ]
