# Generated by Django 3.2.5 on 2023-06-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20230619_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='Tipo_de_reclamo',
            field=models.CharField(choices=[('mala atención', 'Mala atención'), ('local en mal estado', 'Local en mal estado'), ('otro', 'Otro')], default='Otro', max_length=100),
        ),
    ]
