# Generated by Django 3.2.5 on 2023-06-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20230619_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
    ]
