# Generated by Django 3.2.5 on 2023-06-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_alter_claim_tipo_de_reclamo'),
        ('operation', '0008_remove_invoice_total'),
    ]

    operations = [
    ]
